--------------------------------------------------------
--  파일이 생성됨 - 목요일-10월-08-2015   
--------------------------------------------------------
DROP TABLE "KIRA"."BOARD" cascade constraints;
DROP TABLE "KIRA"."DEPT" cascade constraints;
DROP TABLE "KIRA"."DEPT_CP" cascade constraints;
DROP TABLE "KIRA"."DEPT_T" cascade constraints;
DROP TABLE "KIRA"."GOGEK" cascade constraints;
DROP TABLE "KIRA"."GOGEK_EX" cascade constraints;
DROP TABLE "KIRA"."GOGEK_PR" cascade constraints;
DROP TABLE "KIRA"."INSA" cascade constraints;
DROP TABLE "KIRA"."MEM" cascade constraints;
DROP TABLE "KIRA"."MEMBER" cascade constraints;
DROP TABLE "KIRA"."MEMBER_TEST" cascade constraints;
DROP TABLE "KIRA"."MENU" cascade constraints;
DROP TABLE "KIRA"."MINIBOARD" cascade constraints;
DROP TABLE "KIRA"."ORDERCOOK" cascade constraints;
DROP TABLE "KIRA"."PERPORMANCE" cascade constraints;
DROP TABLE "KIRA"."SAWON" cascade constraints;
DROP TABLE "KIRA"."SAWON_CP" cascade constraints;
DROP TABLE "KIRA"."SAWON_CPP" cascade constraints;
DROP TABLE "KIRA"."SAWON_M" cascade constraints;
DROP TABLE "KIRA"."SAWON_MERGE_T" cascade constraints;
DROP TABLE "KIRA"."SAWON_PR" cascade constraints;
DROP TABLE "KIRA"."SAWON_T" cascade constraints;
DROP TABLE "KIRA"."TEST01" cascade constraints;
DROP TABLE "KIRA"."TESTBOARD" cascade constraints;
DROP TABLE "KIRA"."TESTMEM" cascade constraints;
DROP SEQUENCE "KIRA"."BOARD_SEQ";
DROP SEQUENCE "KIRA"."GOGEK_SEQ";
DROP SEQUENCE "KIRA"."MEMBERTABLE_SEQ";
DROP SEQUENCE "KIRA"."MEM_SEQ";
DROP SEQUENCE "KIRA"."MENU_SEQ";
DROP SEQUENCE "KIRA"."MINIBOARD_SEQ";
DROP SEQUENCE "KIRA"."ORDERCOOK_SEQ";
DROP SEQUENCE "KIRA"."SAWON_SEQ";
DROP SEQUENCE "KIRA"."SQUENCE_MEMBERTEST";
DROP SEQUENCE "KIRA"."TEST01_SEQ";
DROP VIEW "KIRA"."BOARD_VIEW";
DROP VIEW "KIRA"."BOARD_VIEW2";
DROP VIEW "KIRA"."DEPT_SAWON";
DROP VIEW "KIRA"."SAWON_VIEW";
DROP VIEW "KIRA"."SS";
DROP FUNCTION "KIRA"."F_JUMIN";
DROP FUNCTION "KIRA"."F_NAME";
DROP PROCEDURE "KIRA"."GO_IN";
DROP PROCEDURE "KIRA"."GO_SEARCH";
DROP PROCEDURE "KIRA"."GO_SEARCH2";
DROP PROCEDURE "KIRA"."PS_IN";
DROP PROCEDURE "KIRA"."P_SAWON";
--------------------------------------------------------
--  DDL for Sequence BOARD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KIRA"."BOARD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence GOGEK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KIRA"."GOGEK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MEMBERTABLE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KIRA"."MEMBERTABLE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MEM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KIRA"."MEM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MENU_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KIRA"."MENU_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MINIBOARD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KIRA"."MINIBOARD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORDERCOOK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KIRA"."ORDERCOOK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SAWON_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KIRA"."SAWON_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SQUENCE_MEMBERTEST
--------------------------------------------------------

   CREATE SEQUENCE  "KIRA"."SQUENCE_MEMBERTEST"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TEST01_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "KIRA"."TEST01_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "KIRA"."BOARD" 
   (	"NO" NUMBER(8,0), 
	"TITLE" VARCHAR2(100 BYTE), 
	"WRITER" VARCHAR2(45 BYTE), 
	"IMG" VARCHAR2(50 BYTE), 
	"CONTENT" VARCHAR2(400 BYTE), 
	"HIT" NUMBER(5,0), 
	"GROUPNO" NUMBER(3,0), 
	"REGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPT
--------------------------------------------------------

  CREATE TABLE "KIRA"."DEPT" 
   (	"DEPTNO" NUMBER(3,0), 
	"DNAME" VARCHAR2(10 BYTE), 
	"LOC" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPT_CP
--------------------------------------------------------

  CREATE TABLE "KIRA"."DEPT_CP" 
   (	"DEPTNO" NUMBER(3,0), 
	"DNAME" VARCHAR2(10 BYTE), 
	"LOC" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPT_T
--------------------------------------------------------

  CREATE TABLE "KIRA"."DEPT_T" 
   (	"DEPTNO" NUMBER(3,0), 
	"DNAME" VARCHAR2(10 BYTE), 
	"LOC" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GOGEK
--------------------------------------------------------

  CREATE TABLE "KIRA"."GOGEK" 
   (	"GOBUN" NUMBER(3,0), 
	"GONAME" VARCHAR2(10 BYTE), 
	"GOTEL" VARCHAR2(18 BYTE), 
	"GOJUMIN" CHAR(14 BYTE), 
	"GODAM" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GOGEK_EX
--------------------------------------------------------

  CREATE TABLE "KIRA"."GOGEK_EX" 
   (	"GOBUN" NUMBER(3,0), 
	"GONAME" VARCHAR2(10 BYTE), 
	"GOTEL" VARCHAR2(18 BYTE), 
	"GOJUMIN" CHAR(14 BYTE), 
	"GODAM" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GOGEK_PR
--------------------------------------------------------

  CREATE TABLE "KIRA"."GOGEK_PR" 
   (	"GOBUN" NUMBER(3,0), 
	"GONAME" VARCHAR2(10 BYTE), 
	"GOTEL" VARCHAR2(18 BYTE), 
	"GOJUMIN" CHAR(14 BYTE), 
	"GODAM" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INSA
--------------------------------------------------------

  CREATE TABLE "KIRA"."INSA" 
   (	"NUM" NUMBER(5,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"SSN" VARCHAR2(14 BYTE), 
	"IBSADATE" DATE, 
	"CITY" VARCHAR2(10 BYTE), 
	"TEL" VARCHAR2(15 BYTE), 
	"BUSEO" VARCHAR2(15 BYTE), 
	"JIKWI" VARCHAR2(15 BYTE), 
	"BASICPAY" NUMBER(10,0), 
	"SUDANG" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEM
--------------------------------------------------------

  CREATE TABLE "KIRA"."MEM" 
   (	"NUM" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"PWD" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(45 BYTE), 
	"POST" CHAR(10 BYTE), 
	"ROADADDRESS" VARCHAR2(300 BYTE), 
	"JIBUNADDRESS" VARCHAR2(300 BYTE), 
	"EDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "KIRA"."MEMBER" 
   (	"NUM" NUMBER, 
	"NAME" VARCHAR2(34 BYTE), 
	"TEL" VARCHAR2(35 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER_TEST
--------------------------------------------------------

  CREATE TABLE "KIRA"."MEMBER_TEST" 
   (	"NUM" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"TEL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "KIRA"."MENU" 
   (	"MNO" NUMBER(3,0), 
	"MCODE" VARCHAR2(45 BYTE), 
	"MNAME" VARCHAR2(45 BYTE), 
	"MPRICE" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MINIBOARD
--------------------------------------------------------

  CREATE TABLE "KIRA"."MINIBOARD" 
   (	"NUM" NUMBER(10,0), 
	"SUB" VARCHAR2(100 BYTE), 
	"WRITER" VARCHAR2(34 BYTE), 
	"CONT" CLOB, 
	"REIP" VARCHAR2(40 BYTE), 
	"BDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ORDERCOOK
--------------------------------------------------------

  CREATE TABLE "KIRA"."ORDERCOOK" 
   (	"ONO" NUMBER(10,0), 
	"MNO" NUMBER(10,0), 
	"ONAME" VARCHAR2(45 BYTE), 
	"QTY" NUMBER(20,0), 
	"ODATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERPORMANCE
--------------------------------------------------------

  CREATE TABLE "KIRA"."PERPORMANCE" 
   (	"ID" VARCHAR2(10 BYTE), 
	"PWV" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SAWON
--------------------------------------------------------

  CREATE TABLE "KIRA"."SAWON" 
   (	"SABUN" NUMBER(3,0), 
	"SANAME" VARCHAR2(20 BYTE), 
	"DEPTNO" NUMBER(3,0), 
	"SAJOB" VARCHAR2(15 BYTE), 
	"SAPAY" NUMBER(10,0), 
	"SAHIRE" DATE, 
	"SASEX" CHAR(6 BYTE), 
	"SAMGR" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SAWON_CP
--------------------------------------------------------

  CREATE TABLE "KIRA"."SAWON_CP" 
   (	"SABUN" NUMBER(3,0), 
	"SANAME" VARCHAR2(20 BYTE), 
	"DEPTNO" NUMBER(3,0), 
	"SAJOB" VARCHAR2(15 BYTE), 
	"SAPAY" NUMBER(10,0), 
	"SAHIRE" DATE, 
	"SASEX" CHAR(6 BYTE), 
	"SAMGR" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SAWON_CPP
--------------------------------------------------------

  CREATE TABLE "KIRA"."SAWON_CPP" 
   (	"SABUN" NUMBER(3,0), 
	"SANAME" VARCHAR2(20 BYTE), 
	"DEPTNO" NUMBER(3,0), 
	"SAJOB" VARCHAR2(15 BYTE), 
	"SAPAY" NUMBER(10,0), 
	"SAHIRE" DATE, 
	"SASEX" CHAR(6 BYTE), 
	"SAMGR" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SAWON_M
--------------------------------------------------------

  CREATE TABLE "KIRA"."SAWON_M" 
   (	"SABUN" NUMBER(3,0), 
	"SANAME" VARCHAR2(20 BYTE), 
	"DEPTNO" NUMBER(3,0), 
	"SAJOB" VARCHAR2(15 BYTE), 
	"SAPAY" NUMBER(10,0), 
	"SAHIRE" DATE, 
	"SASEX" CHAR(6 BYTE), 
	"SAMGR" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SAWON_MERGE_T
--------------------------------------------------------

  CREATE TABLE "KIRA"."SAWON_MERGE_T" 
   (	"SABUN" NUMBER(3,0), 
	"DEPTNO" NUMBER(3,0), 
	"SAPAY" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SAWON_PR
--------------------------------------------------------

  CREATE TABLE "KIRA"."SAWON_PR" 
   (	"SABUN" NUMBER(3,0), 
	"SANAME" VARCHAR2(20 BYTE), 
	"DEPTNO" NUMBER(3,0), 
	"SAJOB" VARCHAR2(15 BYTE), 
	"SAPAY" NUMBER(10,0), 
	"SAHIRE" DATE, 
	"SASEX" CHAR(6 BYTE), 
	"SAMGR" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SAWON_T
--------------------------------------------------------

  CREATE TABLE "KIRA"."SAWON_T" 
   (	"SABUN" NUMBER(3,0), 
	"SANAME" VARCHAR2(20 BYTE), 
	"DEPTNO" NUMBER(3,0), 
	"SAJOB" VARCHAR2(15 BYTE), 
	"SAPAY" NUMBER(10,0), 
	"SAHIRE" DATE, 
	"SASEX" CHAR(6 BYTE), 
	"SAMGR" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEST01
--------------------------------------------------------

  CREATE TABLE "KIRA"."TEST01" 
   (	"NUM" NUMBER, 
	"MSG" VARCHAR2(50 BYTE), 
	"EDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TESTBOARD
--------------------------------------------------------

  CREATE TABLE "KIRA"."TESTBOARD" 
   (	"NID" NUMBER, 
	"SUJECT" VARCHAR2(200 BYTE), 
	"AUTHOR" VARCHAR2(40 BYTE), 
	"PWD" VARCHAR2(100 BYTE), 
	"IP" VARCHAR2(40 BYTE), 
	"R_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TESTMEM
--------------------------------------------------------

  CREATE TABLE "KIRA"."TESTMEM" 
   (	"NUM" NUMBER, 
	"ID" VARCHAR2(10 BYTE), 
	"PWD" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"GENDER" CHAR(6 BYTE), 
	"REGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for View BOARD_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "KIRA"."BOARD_VIEW" ("NUM", "SUB", "WRITER", "PWD", "CONT", "REIP", "REDATE") AS 
  SELECT "NUM","SUB","WRITER","PWD","CONT","REIP","REDATE" FROM BOARD;
--------------------------------------------------------
--  DDL for View BOARD_VIEW2
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "KIRA"."BOARD_VIEW2" ("NUM", "SUB", "REIP", "REDATE") AS 
  SELECT NUM, SUB , REIP , REDATE FROM BOARD
WHERE 1=1 WITH READ ONLY;
--------------------------------------------------------
--  DDL for View DEPT_SAWON
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "KIRA"."DEPT_SAWON" ("SANAME", "SAPAY", "DNAME") AS 
  SELECT s.saname , s.sapay , d.dname from sawon_cp s, dept_cp d
WHERE s.deptno = d.deptno and s.sapay > 3000;
--------------------------------------------------------
--  DDL for View SAWON_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "KIRA"."SAWON_VIEW" ("SABUN", "SANAME", "DEPTNO", "SAJOB", "SAPAY", "SAHIRE", "SASEX", "SAMGR") AS 
  SELECT "SABUN","SANAME","DEPTNO","SAJOB","SAPAY","SAHIRE","SASEX","SAMGR" FROM SAWON;
--------------------------------------------------------
--  DDL for View SS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "KIRA"."SS" ("SANAME", "SAPAY") AS 
  SELECT saname, sapay FROM SAWON ORDER BY SAPAY DESC;
REM INSERTING into KIRA.BOARD
SET DEFINE OFF;
Insert into KIRA.BOARD (NO,TITLE,WRITER,IMG,CONTENT,HIT,GROUPNO,REGDATE) values (42,'����','������','TODO ����Ʈ �߰�.PNG','��������',0,0,to_date('15/10/07','RR/MM/DD'));
Insert into KIRA.BOARD (NO,TITLE,WRITER,IMG,CONTENT,HIT,GROUPNO,REGDATE) values (64,'dsfdsfsd','fdsfsdfsd','TODO 리스트 추가.PNG','dsaddsada',3,200,to_date('15/10/08','RR/MM/DD'));
Insert into KIRA.BOARD (NO,TITLE,WRITER,IMG,CONTENT,HIT,GROUPNO,REGDATE) values (49,'dasd','dasdas','프로젝트 추가됨.PNG','dddd',5,300,to_date('15/10/07','RR/MM/DD'));
Insert into KIRA.BOARD (NO,TITLE,WRITER,IMG,CONTENT,HIT,GROUPNO,REGDATE) values (40,'�����̴� ! ','dasdasd','TODO1.PNG','ddddsadasdas',1,300,to_date('15/10/07','RR/MM/DD'));
Insert into KIRA.BOARD (NO,TITLE,WRITER,IMG,CONTENT,HIT,GROUPNO,REGDATE) values (47,'한글 검사 ','한글 검사 ','디펙토리구조.PNG','한글 검사 ',4,100,to_date('15/10/07','RR/MM/DD'));
Insert into KIRA.BOARD (NO,TITLE,WRITER,IMG,CONTENT,HIT,GROUPNO,REGDATE) values (51,'이제좀 게시판이네 ','나다 ','리스트 화면 @.PNG','ㅇㅇㅇㅇ',22,100,to_date('15/10/07','RR/MM/DD'));
Insert into KIRA.BOARD (NO,TITLE,WRITER,IMG,CONTENT,HIT,GROUPNO,REGDATE) values (65,'dsdfds','fdsfsdfsdf','디펙토리구조.PNG','dsadsad',0,200,to_date('15/10/08','RR/MM/DD'));
Insert into KIRA.BOARD (NO,TITLE,WRITER,IMG,CONTENT,HIT,GROUPNO,REGDATE) values (44,'dasdasd','asdasdas','TODO ī���ڸ� ����.PNG','ddd',1,300,to_date('15/10/07','RR/MM/DD'));
Insert into KIRA.BOARD (NO,TITLE,WRITER,IMG,CONTENT,HIT,GROUPNO,REGDATE) values (46,'����','������','����Ʈ ȭ��.PNG','��������',3,300,to_date('15/10/07','RR/MM/DD'));
Insert into KIRA.BOARD (NO,TITLE,WRITER,IMG,CONTENT,HIT,GROUPNO,REGDATE) values (48,'dasdasd','dasdas','TODO1.PNG','d',1,100,to_date('15/10/07','RR/MM/DD'));
Insert into KIRA.BOARD (NO,TITLE,WRITER,IMG,CONTENT,HIT,GROUPNO,REGDATE) values (50,'dasdsad','dsad','수정 폼.PNG','dddd',5,200,to_date('15/10/07','RR/MM/DD'));
Insert into KIRA.BOARD (NO,TITLE,WRITER,IMG,CONTENT,HIT,GROUPNO,REGDATE) values (37,'sdasdas','dasdasd','TODO1.PNG','ddd',0,100,to_date('15/10/07','RR/MM/DD'));
Insert into KIRA.BOARD (NO,TITLE,WRITER,IMG,CONTENT,HIT,GROUPNO,REGDATE) values (43,'����','������','TODO ����Ʈ �߰�.PNG','��������',0,0,to_date('15/10/07','RR/MM/DD'));
Insert into KIRA.BOARD (NO,TITLE,WRITER,IMG,CONTENT,HIT,GROUPNO,REGDATE) values (39,'rewqdasdsadasd','dasdasd','Struts2-Architecture.png','ddddsadasdas',3,300,to_date('15/10/07','RR/MM/DD'));
Insert into KIRA.BOARD (NO,TITLE,WRITER,IMG,CONTENT,HIT,GROUPNO,REGDATE) values (61,'asasss','sss','TODO 추가.PNG','d',19,100,to_date('15/10/08','RR/MM/DD'));
Insert into KIRA.BOARD (NO,TITLE,WRITER,IMG,CONTENT,HIT,GROUPNO,REGDATE) values (62,'dsdsd','sdsd','리스트 화면 @.PNG','dddd',3,100,to_date('15/10/08','RR/MM/DD'));
Insert into KIRA.BOARD (NO,TITLE,WRITER,IMG,CONTENT,HIT,GROUPNO,REGDATE) values (66,'dsadasd','dsadasd','ddsdsdsdsdsd.PNG','fsdsdgfggfdgfd',2,200,to_date('15/10/08','RR/MM/DD'));
Insert into KIRA.BOARD (NO,TITLE,WRITER,IMG,CONTENT,HIT,GROUPNO,REGDATE) values (41,'�����̴� ! ','dasdasd','TODO ����Ʈ �߰�.PNG','ddddsadasdas',2,300,to_date('15/10/07','RR/MM/DD'));
Insert into KIRA.BOARD (NO,TITLE,WRITER,IMG,CONTENT,HIT,GROUPNO,REGDATE) values (1,'dasdas','asdasd','���� ��.PNG','ddd',0,300,to_date('15/10/07','RR/MM/DD'));
Insert into KIRA.BOARD (NO,TITLE,WRITER,IMG,CONTENT,HIT,GROUPNO,REGDATE) values (63,'dsdsad','dsadasd','TODO 추가.PNG','dddd',2,200,to_date('15/10/08','RR/MM/DD'));
Insert into KIRA.BOARD (NO,TITLE,WRITER,IMG,CONTENT,HIT,GROUPNO,REGDATE) values (36,'sdasdas','dasdasd','����Ʈ ȭ�� @.PNG','ddd',0,100,to_date('15/10/07','RR/MM/DD'));
Insert into KIRA.BOARD (NO,TITLE,WRITER,IMG,CONTENT,HIT,GROUPNO,REGDATE) values (38,'rewqdasdsadasd','dasdasd','Struts2-Architecture.png','ddddsadasdas',11,300,to_date('15/10/07','RR/MM/DD'));
REM INSERTING into KIRA.DEPT
SET DEFINE OFF;
Insert into KIRA.DEPT (DEPTNO,DNAME,LOC) values (60,'기술시','연기');
Insert into KIRA.DEPT (DEPTNO,DNAME,LOC) values (70,'기술일','서울');
Insert into KIRA.DEPT (DEPTNO,DNAME,LOC) values (10,'총무부','서울');
Insert into KIRA.DEPT (DEPTNO,DNAME,LOC) values (20,'영업부','대전');
Insert into KIRA.DEPT (DEPTNO,DNAME,LOC) values (30,'전산부','부산');
Insert into KIRA.DEPT (DEPTNO,DNAME,LOC) values (40,'관리부','광주');
Insert into KIRA.DEPT (DEPTNO,DNAME,LOC) values (50,'개발부','판교');
REM INSERTING into KIRA.DEPT_CP
SET DEFINE OFF;
Insert into KIRA.DEPT_CP (DEPTNO,DNAME,LOC) values (60,'기술시','연기');
Insert into KIRA.DEPT_CP (DEPTNO,DNAME,LOC) values (70,'기술일','서울');
Insert into KIRA.DEPT_CP (DEPTNO,DNAME,LOC) values (10,'총무부','서울');
Insert into KIRA.DEPT_CP (DEPTNO,DNAME,LOC) values (20,'영업부','대전');
Insert into KIRA.DEPT_CP (DEPTNO,DNAME,LOC) values (30,'전산부','부산');
Insert into KIRA.DEPT_CP (DEPTNO,DNAME,LOC) values (40,'관리부','광주');
Insert into KIRA.DEPT_CP (DEPTNO,DNAME,LOC) values (50,'개발부','판교');
REM INSERTING into KIRA.DEPT_T
SET DEFINE OFF;
Insert into KIRA.DEPT_T (DEPTNO,DNAME,LOC) values (60,'기술시','연기');
Insert into KIRA.DEPT_T (DEPTNO,DNAME,LOC) values (70,'기술일','서울');
Insert into KIRA.DEPT_T (DEPTNO,DNAME,LOC) values (10,'총무부','서울');
Insert into KIRA.DEPT_T (DEPTNO,DNAME,LOC) values (20,'영업부','대전');
Insert into KIRA.DEPT_T (DEPTNO,DNAME,LOC) values (30,'전산부','부산');
Insert into KIRA.DEPT_T (DEPTNO,DNAME,LOC) values (40,'관리부','광주');
Insert into KIRA.DEPT_T (DEPTNO,DNAME,LOC) values (50,'개발부','판교');
REM INSERTING into KIRA.GOGEK
SET DEFINE OFF;
Insert into KIRA.GOGEK (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (1,'류민','123-1234','700113-1537915',3);
Insert into KIRA.GOGEK (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (2,'강민','343-1454','690216-1627914',2);
Insert into KIRA.GOGEK (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (3,'영희','144-1655','750320-2636215',null);
Insert into KIRA.GOGEK (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (4,'철이','673-1674','770430-1234567',4);
Insert into KIRA.GOGEK (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (5,'류완','123-1674','720521-1123675',3);
Insert into KIRA.GOGEK (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (6,'캔디','673-1764','650725-2534566',null);
Insert into KIRA.GOGEK (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (7,'똘이','176-7677','630608-1648614',7);
Insert into KIRA.GOGEK (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (8,'쇠돌','673-6774','051010-3346574',9);
Insert into KIRA.GOGEK (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (9,'홍이','767-1234','040811-4234689',17);
Insert into KIRA.GOGEK (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (10,'안나','767-1677','751015-2432168',4);
REM INSERTING into KIRA.GOGEK_EX
SET DEFINE OFF;
Insert into KIRA.GOGEK_EX (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (1,'류민','123-1234','700113-1537915',3);
Insert into KIRA.GOGEK_EX (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (2,'강민','343-1454','690216-1627914',2);
Insert into KIRA.GOGEK_EX (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (3,'영희','144-1655','750320-2636215',null);
Insert into KIRA.GOGEK_EX (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (4,'철이','673-1674','770430-1234567',4);
Insert into KIRA.GOGEK_EX (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (5,'류완','123-1674','720521-1123675',3);
Insert into KIRA.GOGEK_EX (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (6,'캔디','673-1764','650725-2534566',null);
Insert into KIRA.GOGEK_EX (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (7,'똘이','176-7677','630608-1648614',7);
Insert into KIRA.GOGEK_EX (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (8,'쇠돌','673-6774','051010-3346574',9);
Insert into KIRA.GOGEK_EX (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (9,'홍이','767-1234','040811-4234689',17);
Insert into KIRA.GOGEK_EX (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (10,'안나','767-1677','751015-2432168',4);
REM INSERTING into KIRA.GOGEK_PR
SET DEFINE OFF;
Insert into KIRA.GOGEK_PR (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (1,'류민','123-1234','700113-1537915',3);
Insert into KIRA.GOGEK_PR (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (2,'강민','343-1454','690216-1627914',2);
Insert into KIRA.GOGEK_PR (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (3,'영희','144-1655','750320-2636215',null);
Insert into KIRA.GOGEK_PR (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (4,'철이','673-1674','770430-1234567',4);
Insert into KIRA.GOGEK_PR (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (5,'류완','123-1674','720521-1123675',3);
Insert into KIRA.GOGEK_PR (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (6,'캔디','673-1764','650725-2534566',null);
Insert into KIRA.GOGEK_PR (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (7,'똘이','176-7677','630608-1648614',7);
Insert into KIRA.GOGEK_PR (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (8,'쇠돌','673-6774','051010-3346574',9);
Insert into KIRA.GOGEK_PR (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (9,'홍이','767-1234','040811-4234689',17);
Insert into KIRA.GOGEK_PR (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (10,'안나','767-1677','751015-2432168',4);
Insert into KIRA.GOGEK_PR (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (20,'kira','1234-456','123111-23222  ',2);
Insert into KIRA.GOGEK_PR (GOBUN,GONAME,GOTEL,GOJUMIN,GODAM) values (21,'김병기','1234-123','911221-12345  ',2);
REM INSERTING into KIRA.INSA
SET DEFINE OFF;
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1001,'홍길동','771212-1022432',to_date('98/10/11','RR/MM/DD'),'서울','011-2356-4528','기획부','부장',2610000,200000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1002,'김무리','801007-1544236',to_date('00/11/29','RR/MM/DD'),'경기','010-4758-6532','총무부','사원',1320000,200000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1003,'이순애','770922-2312547',to_date('99/02/25','RR/MM/DD'),'인천','010-4231-1236','개발부','부장',2550000,160000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1004,'김정훈','790304-1788896',to_date('00/10/01','RR/MM/DD'),'전북','019-5236-4221','영업부','대리',1954200,170000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1005,'한석봉','811112-1566789',to_date('04/08/13','RR/MM/DD'),'서울','018-5211-3542','총무부','사원',1420000,160000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1006,'이기자','780505-2978541',to_date('02/02/11','RR/MM/DD'),'인천','010-3214-5357','개발부','과장',2265000,150000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1007,'장인철','780506-1625148',to_date('98/03/16','RR/MM/DD'),'제주','011-2345-2525','개발부','대리',1250000,150000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1008,'김영년','821011-2362514',to_date('02/04/30','RR/MM/DD'),'서울','016-2222-4444','홍보부','사원',950000,145000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1009,'나윤균','810810-1552147',to_date('03/10/10','RR/MM/DD'),'경기','019-1111-2222','인사부','사원',840000,220400);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1010,'김종서','751010-1122233',to_date('97/08/08','RR/MM/DD'),'부산','011-3214-5555','영업부','부장',2540000,130000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1011,'유관순','801010-2987897',to_date('00/07/07','RR/MM/DD'),'서울','010-8888-4422','영업부','사원',1020000,140000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1012,'정한국','760909-1333333',to_date('99/10/16','RR/MM/DD'),'강원','018-2222-4242','홍보부','사원',880000,114000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1013,'조미숙','790102-2777777',to_date('98/06/07','RR/MM/DD'),'경기','019-6666-4444','홍보부','대리',1601000,103000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1014,'황진이','810707-2574812',to_date('02/02/15','RR/MM/DD'),'인천','010-3214-5467','개발부','사원',1100000,130000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1015,'이현숙','800606-2954687',to_date('99/07/26','RR/MM/DD'),'경기','016-2548-3365','총무부','사원',1050000,104000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1016,'이상헌','781010-1666678',to_date('01/11/29','RR/MM/DD'),'경기','010-4526-1234','개발부','과장',2350000,150000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1017,'엄용수','820507-1452365',to_date('00/08/28','RR/MM/DD'),'인천','010-3254-2542','개발부','사원',950000,210000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1018,'이성길','801028-1849534',to_date('04/08/08','RR/MM/DD'),'전북','018-1333-3333','개발부','사원',880000,123000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1019,'박문수','780710-1985632',to_date('99/12/10','RR/MM/DD'),'서울','017-4747-4848','인사부','과장',2300000,165000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1020,'유영희','800304-2741258',to_date('03/10/10','RR/MM/DD'),'전남','011-9595-8585','자재부','사원',880000,140000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1021,'홍길남','801010-1111111',to_date('01/09/07','RR/MM/DD'),'경기','011-9999-7575','개발부','사원',875000,120000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1022,'이영숙','800501-2312456',to_date('03/02/25','RR/MM/DD'),'전남','017-5214-5282','기획부','대리',1960000,180000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1023,'김인수','731211-1214576',to_date('95/02/23','RR/MM/DD'),'서울',null,'영업부','부장',2500000,170000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1024,'김말자','830225-2633334',to_date('99/08/28','RR/MM/DD'),'서울','011-5248-7789','기획부','대리',1900000,170000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1025,'우재옥','801103-1654442',to_date('00/10/01','RR/MM/DD'),'서울','010-4563-2587','영업부','사원',1100000,160000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1026,'김숙남','810907-2015457',to_date('02/08/28','RR/MM/DD'),'경기','010-2112-5225','영업부','사원',1050000,150000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1027,'김영길','801216-1898752',to_date('00/10/18','RR/MM/DD'),'서울','019-8523-1478','총무부','과장',2340000,170000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1028,'이남신','810101-1010101',to_date('01/09/07','RR/MM/DD'),'제주','016-1818-4848','인사부','사원',892000,110000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1029,'김말숙','800301-2020202',to_date('00/09/08','RR/MM/DD'),'서울','016-3535-3636','총무부','사원',920000,124000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1030,'정정해','790210-2101010',to_date('99/10/17','RR/MM/DD'),'부산','019-6564-6752','총무부','과장',2304000,124000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1031,'지재환','771115-1687988',to_date('01/01/21','RR/MM/DD'),'서울','019-5552-7511','기획부','부장',2450000,160000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1032,'심심해','810206-2222222',to_date('00/05/05','RR/MM/DD'),'전북','016-8888-7474','자재부','사원',880000,108000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1033,'김미나','780505-2999999',to_date('98/06/07','RR/MM/DD'),'서울','011-2444-4444','영업부','사원',1020000,104000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1034,'이정석','820505-1325468',to_date('05/09/26','RR/MM/DD'),'경기','011-3697-7412','기획부','사원',1100000,160000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1035,'정영희','831010-2153252',to_date('02/05/16','RR/MM/DD'),'인천',null,'개발부','사원',1050000,140000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1036,'이재영','701126-2852147',to_date('03/08/10','RR/MM/DD'),'서울','011-9999-9999','자재부','사원',960400,190000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1037,'최석규','770129-1456987',to_date('98/10/15','RR/MM/DD'),'인천','011-7777-7777','홍보부','과장',2350000,187000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1038,'손인수','791009-2321456',to_date('99/11/15','RR/MM/DD'),'부산','010-6542-7412','영업부','대리',2000000,150000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1039,'고순정','800504-2000032',to_date('03/12/28','RR/MM/DD'),'경기','010-2587-7895','영업부','대리',2010000,160000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1040,'박세열','790509-1635214',to_date('00/09/10','RR/MM/DD'),'경북','016-4444-7777','인사부','대리',2100000,130000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1041,'문길수','721217-1951357',to_date('01/12/10','RR/MM/DD'),'충남','016-4444-5555','자재부','과장',2300000,150000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1042,'채정희','810709-2000054',to_date('03/10/17','RR/MM/DD'),'경기','011-5125-5511','개발부','사원',1020000,200000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1043,'양미옥','830504-2471523',to_date('03/09/24','RR/MM/DD'),'서울','016-8548-6547','영업부','사원',1100000,210000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1044,'지수환','820305-1475286',to_date('04/01/21','RR/MM/DD'),'서울','011-5555-7548','영업부','사원',1060000,220000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1045,'홍원신','690906-1985214',to_date('03/03/16','RR/MM/DD'),'전북','011-7777-7777','영업부','사원',960000,152000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1046,'허경운','760105-1458752',to_date('99/05/04','RR/MM/DD'),'경남','017-3333-3333','총무부','부장',2650000,150000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1047,'산마루','780505-1234567',to_date('01/07/15','RR/MM/DD'),'서울','018-0505-0505','영업부','대리',2100000,112000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1048,'이기상','790604-1415141',to_date('01/06/07','RR/MM/DD'),'전남',null,'개발부','대리',2050000,106000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1049,'이미성','830908-2456548',to_date('00/04/07','RR/MM/DD'),'인천','010-6654-8854','개발부','사원',1300000,130000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1050,'이미인','810403-2828287',to_date('03/06/07','RR/MM/DD'),'경기','011-8585-5252','홍보부','대리',1950000,103000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1051,'권영미','790303-2155554',to_date('00/06/04','RR/MM/DD'),'서울','011-5555-7548','영업부','과장',2260000,104000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1052,'권옥경','820406-2000456',to_date('00/10/10','RR/MM/DD'),'경기','010-3644-5577','기획부','사원',1020000,105000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1053,'김싱식','800715-1313131',to_date('99/12/12','RR/MM/DD'),'전북','011-7585-7474','자재부','사원',960000,108000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1054,'정상호','810705-1212141',to_date('99/10/16','RR/MM/DD'),'강원','016-1919-4242','홍보부','사원',980000,114000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1055,'정한나','820506-2425153',to_date('04/06/07','RR/MM/DD'),'서울','016-2424-4242','영업부','사원',1000000,104000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1056,'전용재','800605-1456987',to_date('04/08/13','RR/MM/DD'),'인천','010-7549-8654','영업부','대리',1950000,200000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1057,'이미경','780406-2003214',to_date('98/02/11','RR/MM/DD'),'경기','016-6542-7546','자재부','부장',2520000,160000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1058,'김신제','800709-1321456',to_date('03/08/08','RR/MM/DD'),'인천','010-2415-5444','기획부','대리',1950000,180000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1059,'임수봉','810809-2121244',to_date('01/10/10','RR/MM/DD'),'서울','011-4151-4154','개발부','사원',890000,102000);
Insert into KIRA.INSA (NUM,NAME,SSN,IBSADATE,CITY,TEL,BUSEO,JIKWI,BASICPAY,SUDANG) values (1060,'김신애','810809-2111111',to_date('01/10/10','RR/MM/DD'),'서울','011-4151-4444','개발부','사원',900000,102000);
REM INSERTING into KIRA.MEM
SET DEFINE OFF;
Insert into KIRA.MEM (NUM,ID,PWD,NAME,POST,ROADADDRESS,JIBUNADDRESS,EDATE) values (1,'dsadasd','sadsad','sadasdasd','13536     ','경기 성남시 분당구 판교역로 4 (백현동)','경기 성남시 분당구 백현동 582-7',to_date('15/10/01','RR/MM/DD'));
Insert into KIRA.MEM (NUM,ID,PWD,NAME,POST,ROADADDRESS,JIBUNADDRESS,EDATE) values (4,'12345','ddddd','sadasdasd','34672     ','123','123',to_date('15/10/01','RR/MM/DD'));
Insert into KIRA.MEM (NUM,ID,PWD,NAME,POST,ROADADDRESS,JIBUNADDRESS,EDATE) values (5000000,'wwww','1234','dasdasdsa','dasdas    ','saddsa','asdsad',to_date('15/10/13','RR/MM/DD'));
Insert into KIRA.MEM (NUM,ID,PWD,NAME,POST,ROADADDRESS,JIBUNADDRESS,EDATE) values (65,'dd','dd','dd','123456    ','주소','지번주소',to_date('15/10/05','RR/MM/DD'));
Insert into KIRA.MEM (NUM,ID,PWD,NAME,POST,ROADADDRESS,JIBUNADDRESS,EDATE) values (67,'TEST04','123456','김수정','42444     ','대구 남구 대덕로 139 (봉덕동)','대구 남구 봉덕동 624-8',to_date('15/10/05','RR/MM/DD'));
Insert into KIRA.MEM (NUM,ID,PWD,NAME,POST,ROADADDRESS,JIBUNADDRESS,EDATE) values (66,'wwww3426','1234','TEST','13536     ','경기 성남시 분당구 판교역로2번길 1 (백현동)','경기 성남시 분당구 백현동 582-6',to_date('15/10/05','RR/MM/DD'));
REM INSERTING into KIRA.MEMBER
SET DEFINE OFF;
REM INSERTING into KIRA.MEMBER_TEST
SET DEFINE OFF;
REM INSERTING into KIRA.MENU
SET DEFINE OFF;
Insert into KIRA.MENU (MNO,MCODE,MNAME,MPRICE) values (61,'JP','초밥',12000);
Insert into KIRA.MENU (MNO,MCODE,MNAME,MPRICE) values (54,'YS','돈까스',10000);
Insert into KIRA.MENU (MNO,MCODE,MNAME,MPRICE) values (55,'YS','비프까스',10000);
Insert into KIRA.MENU (MNO,MCODE,MNAME,MPRICE) values (41,'CH','불도장',10000);
Insert into KIRA.MENU (MNO,MCODE,MNAME,MPRICE) values (56,'YS','스테이',12000);
Insert into KIRA.MENU (MNO,MCODE,MNAME,MPRICE) values (52,'CH','짜장밥',11000);
Insert into KIRA.MENU (MNO,MCODE,MNAME,MPRICE) values (44,'KR','갈비찜',10000);
Insert into KIRA.MENU (MNO,MCODE,MNAME,MPRICE) values (57,'YS','파스타',11000);
Insert into KIRA.MENU (MNO,MCODE,MNAME,MPRICE) values (58,'BS','라면',10000);
Insert into KIRA.MENU (MNO,MCODE,MNAME,MPRICE) values (47,'KR','갈비찜',10000);
Insert into KIRA.MENU (MNO,MCODE,MNAME,MPRICE) values (59,'BS','라볶이',10000);
Insert into KIRA.MENU (MNO,MCODE,MNAME,MPRICE) values (60,'BS','쫄면',10000);
Insert into KIRA.MENU (MNO,MCODE,MNAME,MPRICE) values (53,'KR','갈비찜',13000);
REM INSERTING into KIRA.MINIBOARD
SET DEFINE OFF;
Insert into KIRA.MINIBOARD (NUM,SUB,WRITER,REIP,BDATE) values (1,'12','123','192.112.123.12',to_date('15/10/06','RR/MM/DD'));
Insert into KIRA.MINIBOARD (NUM,SUB,WRITER,REIP,BDATE) values (2,'121212','dsdsd','192.112.123.12',to_date('15/10/06','RR/MM/DD'));
Insert into KIRA.MINIBOARD (NUM,SUB,WRITER,REIP,BDATE) values (3,'331312','dsdsd','192.112.123.12',to_date('15/10/06','RR/MM/DD'));
Insert into KIRA.MINIBOARD (NUM,SUB,WRITER,REIP,BDATE) values (4,'dsds','sdsddsd','192.112.123.12',to_date('15/10/06','RR/MM/DD'));
Insert into KIRA.MINIBOARD (NUM,SUB,WRITER,REIP,BDATE) values (5,'dsds','dsds','192.112.123.12',to_date('15/10/06','RR/MM/DD'));
Insert into KIRA.MINIBOARD (NUM,SUB,WRITER,REIP,BDATE) values (6,'잉여잉여','잉여당','192.112.123.12',to_date('15/10/06','RR/MM/DD'));
REM INSERTING into KIRA.ORDERCOOK
SET DEFINE OFF;
Insert into KIRA.ORDERCOOK (ONO,MNO,ONAME,QTY,ODATE) values (3,41,'김수리',8,to_date('15/09/24','RR/MM/DD'));
Insert into KIRA.ORDERCOOK (ONO,MNO,ONAME,QTY,ODATE) values (4,52,'김병기',5,to_date('15/09/24','RR/MM/DD'));
Insert into KIRA.ORDERCOOK (ONO,MNO,ONAME,QTY,ODATE) values (1,44,'김병기',7,to_date('15/09/24','RR/MM/DD'));
Insert into KIRA.ORDERCOOK (ONO,MNO,ONAME,QTY,ODATE) values (2,47,'김수리',8,to_date('15/09/24','RR/MM/DD'));
Insert into KIRA.ORDERCOOK (ONO,MNO,ONAME,QTY,ODATE) values (5,44,'김병기',4,to_date('15/09/24','RR/MM/DD'));
Insert into KIRA.ORDERCOOK (ONO,MNO,ONAME,QTY,ODATE) values (6,53,' 김병기',5,to_date('15/09/24','RR/MM/DD'));
Insert into KIRA.ORDERCOOK (ONO,MNO,ONAME,QTY,ODATE) values (7,61,'김병기',9,to_date('15/09/24','RR/MM/DD'));
Insert into KIRA.ORDERCOOK (ONO,MNO,ONAME,QTY,ODATE) values (8,44,'주문자',13,to_date('15/09/24','RR/MM/DD'));
Insert into KIRA.ORDERCOOK (ONO,MNO,ONAME,QTY,ODATE) values (21,55,'sdddd',1,to_date('15/09/25','RR/MM/DD'));
REM INSERTING into KIRA.PERPORMANCE
SET DEFINE OFF;
REM INSERTING into KIRA.SAWON
SET DEFINE OFF;
Insert into KIRA.SAWON (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (1,'김길동',10,'회장',5000,to_date('80/01/01','RR/MM/DD'),'남자',null);
Insert into KIRA.SAWON (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (2,'한국남',20,'부장',3000,to_date('88/11/01','RR/MM/DD'),'남자',1);
Insert into KIRA.SAWON (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (3,'이순신',20,'과장',3500,to_date('85/03/01','RR/MM/DD'),'남자',2);
Insert into KIRA.SAWON (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (4,'김소은',20,'사원',1200,to_date('90/05/01','RR/MM/DD'),'여자',3);
Insert into KIRA.SAWON (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (5,'아이유',20,'과장',2300,to_date('96/06/01','RR/MM/DD'),'여자',2);
Insert into KIRA.SAWON (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (6,'류별나',20,'과장',1600,to_date('89/12/01','RR/MM/DD'),'여자',2);
Insert into KIRA.SAWON (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (7,'채시라',20,'사원',3400,to_date('93/10/01','RR/MM/DD'),'여자',3);
Insert into KIRA.SAWON (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (8,'이선계',30,'부장',2803,to_date('84/05/01','RR/MM/DD'),'남자',1);
Insert into KIRA.SAWON (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (9,'무궁화',10,'부장',3000,to_date('96/11/01','RR/MM/DD'),'여자',1);
Insert into KIRA.SAWON (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (10,'임꺽정',20,'사원',2200,to_date('88/04/01','RR/MM/DD'),'남자',7);
Insert into KIRA.SAWON (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (11,'김유신',30,'사원',9000,to_date('81/04/01','RR/MM/DD'),'남자',4);
Insert into KIRA.SAWON (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (12,'공부해',30,'사원',1303,to_date('88/11/01','RR/MM/DD'),'남자',4);
Insert into KIRA.SAWON (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (13,'강감찬',30,'사원',1003,to_date('86/07/01','RR/MM/DD'),'남자',4);
Insert into KIRA.SAWON (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (14,'무궁화',10,'사원',1100,to_date('84/08/01','RR/MM/DD'),'여자',12);
Insert into KIRA.SAWON (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (15,'이미라',30,'대리',2503,to_date('83/04/01','RR/MM/DD'),'여자',10);
Insert into KIRA.SAWON (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (16,'구하라',10,'사원',2000,to_date('91/04/01','RR/MM/DD'),'여자',12);
Insert into KIRA.SAWON (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (17,'깨똥이',10,'과장',4500,to_date('90/05/01','RR/MM/DD'),'남자',13);
Insert into KIRA.SAWON (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (18,'밤선비',50,'과장',4003,to_date('95/05/01','RR/MM/DD'),'남자',17);
Insert into KIRA.SAWON (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (19,'채송화',30,'대리',1703,to_date('92/06/01','RR/MM/DD'),'여자',17);
Insert into KIRA.SAWON (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (20,'류명한',10,'대리',1800,to_date('90/10/01','RR/MM/DD'),'남자',18);
REM INSERTING into KIRA.SAWON_CP
SET DEFINE OFF;
Insert into KIRA.SAWON_CP (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (1,'김길동',10,'회장',5000,to_date('80/01/01','RR/MM/DD'),'남자',null);
Insert into KIRA.SAWON_CP (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (2,'한국남',20,'부장',3000,to_date('88/11/01','RR/MM/DD'),'남자',1);
Insert into KIRA.SAWON_CP (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (3,'이순신',20,'과장',3500,to_date('85/03/01','RR/MM/DD'),'남자',2);
Insert into KIRA.SAWON_CP (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (4,'김소은',20,'사원',1200,to_date('90/05/01','RR/MM/DD'),'여자',3);
Insert into KIRA.SAWON_CP (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (5,'아이유',20,'과장',2300,to_date('96/06/01','RR/MM/DD'),'여자',2);
Insert into KIRA.SAWON_CP (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (6,'류별나',20,'과장',1600,to_date('89/12/01','RR/MM/DD'),'여자',2);
Insert into KIRA.SAWON_CP (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (7,'채시라',20,'사원',3400,to_date('93/10/01','RR/MM/DD'),'여자',3);
Insert into KIRA.SAWON_CP (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (8,'이선계',30,'부장',2803,to_date('84/05/01','RR/MM/DD'),'남자',1);
Insert into KIRA.SAWON_CP (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (9,'무궁화',10,'부장',3000,to_date('96/11/01','RR/MM/DD'),'여자',1);
Insert into KIRA.SAWON_CP (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (10,'임꺽정',20,'사원',2200,to_date('88/04/01','RR/MM/DD'),'남자',7);
Insert into KIRA.SAWON_CP (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (11,'김유신',30,'사원',9000,to_date('81/04/01','RR/MM/DD'),'남자',4);
Insert into KIRA.SAWON_CP (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (12,'공부해',30,'사원',1303,to_date('88/11/01','RR/MM/DD'),'남자',4);
Insert into KIRA.SAWON_CP (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (13,'강감찬',30,'사원',1003,to_date('86/07/01','RR/MM/DD'),'남자',4);
Insert into KIRA.SAWON_CP (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (14,'무궁화',10,'사원',1100,to_date('84/08/01','RR/MM/DD'),'여자',12);
Insert into KIRA.SAWON_CP (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (15,'이미라',30,'대리',2503,to_date('83/04/01','RR/MM/DD'),'여자',10);
Insert into KIRA.SAWON_CP (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (16,'구하라',10,'사원',2000,to_date('91/04/01','RR/MM/DD'),'여자',12);
Insert into KIRA.SAWON_CP (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (17,'깨똥이',10,'과장',4500,to_date('90/05/01','RR/MM/DD'),'남자',13);
Insert into KIRA.SAWON_CP (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (18,'밤선비',50,'과장',4003,to_date('95/05/01','RR/MM/DD'),'남자',17);
Insert into KIRA.SAWON_CP (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (19,'채송화',30,'대리',1703,to_date('92/06/01','RR/MM/DD'),'여자',17);
Insert into KIRA.SAWON_CP (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (20,'류명한',10,'대리',1800,to_date('90/10/01','RR/MM/DD'),'남자',18);
REM INSERTING into KIRA.SAWON_CPP
SET DEFINE OFF;
REM INSERTING into KIRA.SAWON_M
SET DEFINE OFF;
Insert into KIRA.SAWON_M (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (3,'이순신',20,'과장',3500,to_date('85/03/01','RR/MM/DD'),'남자',2);
Insert into KIRA.SAWON_M (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (5,'아이유',20,'과장',2300,to_date('96/06/01','RR/MM/DD'),'여자',2);
Insert into KIRA.SAWON_M (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (6,'류별나',20,'과장',1600,to_date('89/12/01','RR/MM/DD'),'여자',2);
Insert into KIRA.SAWON_M (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (17,'깨똥이',10,'과장',4500,to_date('90/05/01','RR/MM/DD'),'남자',13);
Insert into KIRA.SAWON_M (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (18,'밤선비',50,'과장',4003,to_date('95/05/01','RR/MM/DD'),'남자',17);
REM INSERTING into KIRA.SAWON_MERGE_T
SET DEFINE OFF;
Insert into KIRA.SAWON_MERGE_T (SABUN,DEPTNO,SAPAY) values (1,10,5000);
Insert into KIRA.SAWON_MERGE_T (SABUN,DEPTNO,SAPAY) values (2,20,3000);
Insert into KIRA.SAWON_MERGE_T (SABUN,DEPTNO,SAPAY) values (3,20,3500);
Insert into KIRA.SAWON_MERGE_T (SABUN,DEPTNO,SAPAY) values (4,20,1200);
Insert into KIRA.SAWON_MERGE_T (SABUN,DEPTNO,SAPAY) values (5,20,2300);
Insert into KIRA.SAWON_MERGE_T (SABUN,DEPTNO,SAPAY) values (6,20,1600);
Insert into KIRA.SAWON_MERGE_T (SABUN,DEPTNO,SAPAY) values (7,20,3400);
Insert into KIRA.SAWON_MERGE_T (SABUN,DEPTNO,SAPAY) values (9,10,3000);
Insert into KIRA.SAWON_MERGE_T (SABUN,DEPTNO,SAPAY) values (10,20,2200);
Insert into KIRA.SAWON_MERGE_T (SABUN,DEPTNO,SAPAY) values (14,10,1100);
Insert into KIRA.SAWON_MERGE_T (SABUN,DEPTNO,SAPAY) values (16,10,2000);
Insert into KIRA.SAWON_MERGE_T (SABUN,DEPTNO,SAPAY) values (17,10,4500);
Insert into KIRA.SAWON_MERGE_T (SABUN,DEPTNO,SAPAY) values (20,10,1800);
REM INSERTING into KIRA.SAWON_PR
SET DEFINE OFF;
Insert into KIRA.SAWON_PR (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (1,'김길동',10,'회장',5000,to_date('80/01/01','RR/MM/DD'),'남자',null);
Insert into KIRA.SAWON_PR (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (2,'한국남',20,'부장',3000,to_date('88/11/01','RR/MM/DD'),'남자',1);
Insert into KIRA.SAWON_PR (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (3,'이순신',20,'과장',3500,to_date('85/03/01','RR/MM/DD'),'남자',2);
Insert into KIRA.SAWON_PR (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (4,'김소은',20,'사원',1200,to_date('90/05/01','RR/MM/DD'),'여자',3);
Insert into KIRA.SAWON_PR (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (5,'아이유',20,'과장',2300,to_date('96/06/01','RR/MM/DD'),'여자',2);
Insert into KIRA.SAWON_PR (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (6,'류별나',20,'과장',1600,to_date('89/12/01','RR/MM/DD'),'여자',2);
Insert into KIRA.SAWON_PR (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (7,'채시라',20,'사원',3400,to_date('93/10/01','RR/MM/DD'),'여자',3);
Insert into KIRA.SAWON_PR (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (8,'이선계',30,'부장',2803,to_date('84/05/01','RR/MM/DD'),'남자',1);
Insert into KIRA.SAWON_PR (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (9,'무궁화',10,'부장',3000,to_date('96/11/01','RR/MM/DD'),'여자',1);
Insert into KIRA.SAWON_PR (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (10,'임꺽정',20,'사원',2200,to_date('88/04/01','RR/MM/DD'),'남자',7);
Insert into KIRA.SAWON_PR (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (11,'김유신',30,'사원',9000,to_date('81/04/01','RR/MM/DD'),'남자',4);
Insert into KIRA.SAWON_PR (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (12,'공부해',30,'사원',1303,to_date('88/11/01','RR/MM/DD'),'남자',4);
Insert into KIRA.SAWON_PR (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (13,'강감찬',30,'사원',1003,to_date('86/07/01','RR/MM/DD'),'남자',4);
Insert into KIRA.SAWON_PR (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (14,'무궁화',10,'사원',1100,to_date('84/08/01','RR/MM/DD'),'여자',12);
Insert into KIRA.SAWON_PR (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (15,'이미라',30,'대리',2503,to_date('83/04/01','RR/MM/DD'),'여자',10);
Insert into KIRA.SAWON_PR (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (16,'구하라',10,'사원',2000,to_date('91/04/01','RR/MM/DD'),'여자',12);
Insert into KIRA.SAWON_PR (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (17,'깨똥이',10,'과장',4500,to_date('90/05/01','RR/MM/DD'),'남자',13);
Insert into KIRA.SAWON_PR (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (18,'밤선비',50,'과장',4003,to_date('95/05/01','RR/MM/DD'),'남자',17);
Insert into KIRA.SAWON_PR (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (19,'채송화',30,'대리',1703,to_date('92/06/01','RR/MM/DD'),'여자',17);
Insert into KIRA.SAWON_PR (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (20,'류명한',10,'대리',1800,to_date('90/10/01','RR/MM/DD'),'남자',18);
Insert into KIRA.SAWON_PR (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (21,'김민수',20,'대리',2400,to_date('15/09/16','RR/MM/DD'),'남자',null);
Insert into KIRA.SAWON_PR (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (25,'kira',20,'�븮',1000,to_date('15/09/16','RR/MM/DD'),'��',null);
REM INSERTING into KIRA.SAWON_T
SET DEFINE OFF;
Insert into KIRA.SAWON_T (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (1,'김길동',10,'회장',5000,to_date('80/01/01','RR/MM/DD'),'남자',null);
Insert into KIRA.SAWON_T (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (2,'한국남',20,'부장',3000,to_date('88/11/01','RR/MM/DD'),'남자',1);
Insert into KIRA.SAWON_T (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (3,'이순신',20,'과장',3500,to_date('85/03/01','RR/MM/DD'),'남자',2);
Insert into KIRA.SAWON_T (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (4,'김소은',20,'사원',1200,to_date('90/05/01','RR/MM/DD'),'여자',3);
Insert into KIRA.SAWON_T (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (5,'아이유',20,'과장',2300,to_date('96/06/01','RR/MM/DD'),'여자',2);
Insert into KIRA.SAWON_T (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (6,'류별나',20,'과장',1600,to_date('89/12/01','RR/MM/DD'),'여자',2);
Insert into KIRA.SAWON_T (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (7,'채시라',20,'사원',3400,to_date('93/10/01','RR/MM/DD'),'여자',3);
Insert into KIRA.SAWON_T (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (8,'이선계',30,'부장',2803,to_date('84/05/01','RR/MM/DD'),'남자',1);
Insert into KIRA.SAWON_T (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (9,'무궁화',10,'부장',3000,to_date('96/11/01','RR/MM/DD'),'여자',1);
Insert into KIRA.SAWON_T (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (10,'임꺽정',20,'사원',2200,to_date('88/04/01','RR/MM/DD'),'남자',7);
Insert into KIRA.SAWON_T (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (11,'김유신',30,'사원',9000,to_date('81/04/01','RR/MM/DD'),'남자',4);
Insert into KIRA.SAWON_T (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (12,'공부해',30,'사원',1303,to_date('88/11/01','RR/MM/DD'),'남자',4);
Insert into KIRA.SAWON_T (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (13,'강감찬',30,'사원',1003,to_date('86/07/01','RR/MM/DD'),'남자',4);
Insert into KIRA.SAWON_T (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (14,'무궁화',10,'사원',1100,to_date('84/08/01','RR/MM/DD'),'여자',12);
Insert into KIRA.SAWON_T (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (15,'이미라',30,'대리',2503,to_date('83/04/01','RR/MM/DD'),'여자',10);
Insert into KIRA.SAWON_T (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (16,'구하라',10,'사원',2000,to_date('91/04/01','RR/MM/DD'),'여자',12);
Insert into KIRA.SAWON_T (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (17,'깨똥이',10,'과장',4500,to_date('90/05/01','RR/MM/DD'),'남자',13);
Insert into KIRA.SAWON_T (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (18,'밤선비',50,'과장',4003,to_date('95/05/01','RR/MM/DD'),'남자',17);
Insert into KIRA.SAWON_T (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (19,'채송화',30,'대리',1703,to_date('92/06/01','RR/MM/DD'),'여자',17);
Insert into KIRA.SAWON_T (SABUN,SANAME,DEPTNO,SAJOB,SAPAY,SAHIRE,SASEX,SAMGR) values (20,'류명한',10,'대리',1800,to_date('90/10/01','RR/MM/DD'),'남자',18);
REM INSERTING into KIRA.TEST01
SET DEFINE OFF;
Insert into KIRA.TEST01 (NUM,MSG,EDATE) values (21,'하이1',to_date('15/09/09','RR/MM/DD'));
Insert into KIRA.TEST01 (NUM,MSG,EDATE) values (22,'하이2',to_date('15/09/09','RR/MM/DD'));
Insert into KIRA.TEST01 (NUM,MSG,EDATE) values (23,'하이3',to_date('15/09/09','RR/MM/DD'));
Insert into KIRA.TEST01 (NUM,MSG,EDATE) values (24,'하이4',to_date('15/09/09','RR/MM/DD'));
Insert into KIRA.TEST01 (NUM,MSG,EDATE) values (25,'하이5',to_date('15/09/09','RR/MM/DD'));
Insert into KIRA.TEST01 (NUM,MSG,EDATE) values (26,'하이6',to_date('15/09/09','RR/MM/DD'));
Insert into KIRA.TEST01 (NUM,MSG,EDATE) values (27,'하이7',to_date('15/09/09','RR/MM/DD'));
Insert into KIRA.TEST01 (NUM,MSG,EDATE) values (28,'하이8',to_date('15/09/09','RR/MM/DD'));
Insert into KIRA.TEST01 (NUM,MSG,EDATE) values (29,'하이9',to_date('15/09/09','RR/MM/DD'));
Insert into KIRA.TEST01 (NUM,MSG,EDATE) values (30,'하이10',to_date('15/09/09','RR/MM/DD'));
REM INSERTING into KIRA.TESTBOARD
SET DEFINE OFF;
Insert into KIRA.TESTBOARD (NID,SUJECT,AUTHOR,PWD,IP,R_DATE) values (11,'dd','dd','dd','111.11.111.1',to_date('15/09/08','RR/MM/DD'));
Insert into KIRA.TESTBOARD (NID,SUJECT,AUTHOR,PWD,IP,R_DATE) values (1,'1번글','김병기1','1234','123.123.13.12',to_date('15/09/08','RR/MM/DD'));
Insert into KIRA.TESTBOARD (NID,SUJECT,AUTHOR,PWD,IP,R_DATE) values (2,'2번글','김병기1','1234','123.123.13.12',to_date('15/09/08','RR/MM/DD'));
Insert into KIRA.TESTBOARD (NID,SUJECT,AUTHOR,PWD,IP,R_DATE) values (3,'3번글','김병기2','2452','123.123.1.1',to_date('15/09/08','RR/MM/DD'));
Insert into KIRA.TESTBOARD (NID,SUJECT,AUTHOR,PWD,IP,R_DATE) values (4,'4번글','김병기3','1234','123.143.1.1',to_date('15/09/08','RR/MM/DD'));
Insert into KIRA.TESTBOARD (NID,SUJECT,AUTHOR,PWD,IP,R_DATE) values (5,'5번글','김병기4','1333','112.243.2.1',to_date('15/09/08','RR/MM/DD'));
Insert into KIRA.TESTBOARD (NID,SUJECT,AUTHOR,PWD,IP,R_DATE) values (6,'6번글','김병기5','4511','123.33.3.3',to_date('15/09/08','RR/MM/DD'));
Insert into KIRA.TESTBOARD (NID,SUJECT,AUTHOR,PWD,IP,R_DATE) values (7,'7번글','김병기6','4444','12.33.33.33',to_date('15/09/08','RR/MM/DD'));
Insert into KIRA.TESTBOARD (NID,SUJECT,AUTHOR,PWD,IP,R_DATE) values (8,'8번글','김병기7','4442','212.24.32.33',to_date('15/09/08','RR/MM/DD'));
Insert into KIRA.TESTBOARD (NID,SUJECT,AUTHOR,PWD,IP,R_DATE) values (9,'9번글','김병기8','5566',' 33.232.32.3',to_date('15/09/08','RR/MM/DD'));
Insert into KIRA.TESTBOARD (NID,SUJECT,AUTHOR,PWD,IP,R_DATE) values (10,'10번글','김병기9','1333','123.234.4.4',to_date('15/09/08','RR/MM/DD'));
REM INSERTING into KIRA.TESTMEM
SET DEFINE OFF;
Insert into KIRA.TESTMEM (NUM,ID,PWD,NAME,GENDER,REGDATE) values (11,'kira','kkk','kira','male  ',to_date('15/09/08','RR/MM/DD'));
Insert into KIRA.TESTMEM (NUM,ID,PWD,NAME,GENDER,REGDATE) values (4,'kira','kr','�躴��','��',to_date('15/09/08','RR/MM/DD'));
Insert into KIRA.TESTMEM (NUM,ID,PWD,NAME,GENDER,REGDATE) values (5,'d','d','d','male  ',to_date('15/09/08','RR/MM/DD'));
Insert into KIRA.TESTMEM (NUM,ID,PWD,NAME,GENDER,REGDATE) values (1,'bigdaday','12','김길동','남   ',to_date('15/09/08','RR/MM/DD'));
Insert into KIRA.TESTMEM (NUM,ID,PWD,NAME,GENDER,REGDATE) values (2,'womem','12','김진아','여자',to_date('15/09/08','RR/MM/DD'));
Insert into KIRA.TESTMEM (NUM,ID,PWD,NAME,GENDER,REGDATE) values (3,'womem','12','김수리','남자',to_date('15/09/08','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index TEST01_NUM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIRA"."TEST01_NUM_PK" ON "KIRA"."TEST01" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MENU_MNO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIRA"."MENU_MNO_PK" ON "KIRA"."MENU" ("MNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MB_NUM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIRA"."MB_NUM_PK" ON "KIRA"."MINIBOARD" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBER_TEST_NUM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIRA"."MEMBER_TEST_NUM_PK" ON "KIRA"."MEMBER_TEST" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BOARD_NO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIRA"."BOARD_NO_PK" ON "KIRA"."BOARD" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEM_ID_UQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIRA"."MEM_ID_UQ" ON "KIRA"."MEM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INSA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIRA"."INSA_PK" ON "KIRA"."INSA" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEPT_DEPTNO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIRA"."DEPT_DEPTNO_PK" ON "KIRA"."DEPT" ("DEPTNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEM_NUM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIRA"."MEM_NUM_PK" ON "KIRA"."MEM" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GOGEK_GOBUN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIRA"."GOGEK_GOBUN_PK" ON "KIRA"."GOGEK" ("GOBUN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MEMBER_NUM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIRA"."MEMBER_NUM_PK" ON "KIRA"."MEMBER" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORD_ONO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIRA"."ORD_ONO_PK" ON "KIRA"."ORDERCOOK" ("ONO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DEPT_DNAME_UQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIRA"."DEPT_DNAME_UQ" ON "KIRA"."DEPT" ("DNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GOGEK_GOJUMIN_UQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIRA"."GOGEK_GOJUMIN_UQ" ON "KIRA"."GOGEK" ("GOJUMIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SAWON_SABUN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KIRA"."SAWON_SABUN_PK" ON "KIRA"."SAWON" ("SABUN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table GOGEK_EX
--------------------------------------------------------

  ALTER TABLE "KIRA"."GOGEK_EX" MODIFY ("GOJUMIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEM
--------------------------------------------------------

  ALTER TABLE "KIRA"."MEM" ADD CONSTRAINT "MEM_ID_UQ" UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KIRA"."MEM" ADD CONSTRAINT "MEM_NUM_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KIRA"."MEM" MODIFY ("ID" CONSTRAINT "MEM_ID_NN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GOGEK_PR
--------------------------------------------------------

  ALTER TABLE "KIRA"."GOGEK_PR" MODIFY ("GOJUMIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MINIBOARD
--------------------------------------------------------

  ALTER TABLE "KIRA"."MINIBOARD" ADD CONSTRAINT "MB_NUM_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "KIRA"."MEMBER" ADD CONSTRAINT "MEMBER_NUM_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SAWON
--------------------------------------------------------

  ALTER TABLE "KIRA"."SAWON" ADD CONSTRAINT "SAWON_SABUN_PK" PRIMARY KEY ("SABUN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KIRA"."SAWON" ADD CONSTRAINT "SAWON_SASEX_CK" CHECK (sasex='남자' or sasex='여자') ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER_TEST
--------------------------------------------------------

  ALTER TABLE "KIRA"."MEMBER_TEST" ADD CONSTRAINT "MEMBER_TEST_NUM_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "KIRA"."BOARD" ADD CONSTRAINT "BOARD_NO_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPT
--------------------------------------------------------

  ALTER TABLE "KIRA"."DEPT" ADD CONSTRAINT "DEPT_DNAME_UQ" UNIQUE ("DNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KIRA"."DEPT" ADD CONSTRAINT "DEPT_DEPTNO_PK" PRIMARY KEY ("DEPTNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KIRA"."DEPT" MODIFY ("DNAME" CONSTRAINT "DEPT_DNAME_NN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDERCOOK
--------------------------------------------------------

  ALTER TABLE "KIRA"."ORDERCOOK" ADD CONSTRAINT "ORD_ONO_PK" PRIMARY KEY ("ONO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GOGEK
--------------------------------------------------------

  ALTER TABLE "KIRA"."GOGEK" ADD CONSTRAINT "GOGEK_GOJUMIN_UQ" UNIQUE ("GOJUMIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KIRA"."GOGEK" ADD CONSTRAINT "GOGEK_GOBUN_PK" PRIMARY KEY ("GOBUN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KIRA"."GOGEK" MODIFY ("GOJUMIN" CONSTRAINT "GOGEK_GOJUMIN_NN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INSA
--------------------------------------------------------

  ALTER TABLE "KIRA"."INSA" ADD CONSTRAINT "INSA_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KIRA"."INSA" MODIFY ("SUDANG" NOT NULL ENABLE);
  ALTER TABLE "KIRA"."INSA" MODIFY ("BASICPAY" NOT NULL ENABLE);
  ALTER TABLE "KIRA"."INSA" MODIFY ("JIKWI" NOT NULL ENABLE);
  ALTER TABLE "KIRA"."INSA" MODIFY ("BUSEO" NOT NULL ENABLE);
  ALTER TABLE "KIRA"."INSA" MODIFY ("IBSADATE" NOT NULL ENABLE);
  ALTER TABLE "KIRA"."INSA" MODIFY ("SSN" NOT NULL ENABLE);
  ALTER TABLE "KIRA"."INSA" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEST01
--------------------------------------------------------

  ALTER TABLE "KIRA"."TEST01" ADD CONSTRAINT "TEST01_NUM_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TESTMEM
--------------------------------------------------------

  ALTER TABLE "KIRA"."TESTMEM" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KIRA"."TESTMEM" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "KIRA"."TESTMEM" MODIFY ("PWD" NOT NULL ENABLE);
  ALTER TABLE "KIRA"."TESTMEM" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPT_T
--------------------------------------------------------

  ALTER TABLE "KIRA"."DEPT_T" MODIFY ("DNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPT_CP
--------------------------------------------------------

  ALTER TABLE "KIRA"."DEPT_CP" MODIFY ("DNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TESTBOARD
--------------------------------------------------------

  ALTER TABLE "KIRA"."TESTBOARD" ADD PRIMARY KEY ("NID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KIRA"."TESTBOARD" MODIFY ("IP" NOT NULL ENABLE);
  ALTER TABLE "KIRA"."TESTBOARD" MODIFY ("AUTHOR" NOT NULL ENABLE);
  ALTER TABLE "KIRA"."TESTBOARD" MODIFY ("SUJECT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "KIRA"."MENU" ADD CONSTRAINT "MENU_MNO_PK" PRIMARY KEY ("MNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GOGEK
--------------------------------------------------------

  ALTER TABLE "KIRA"."GOGEK" ADD CONSTRAINT "GOGEK_GODAM_FK" FOREIGN KEY ("GODAM")
	  REFERENCES "KIRA"."SAWON" ("SABUN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDERCOOK
--------------------------------------------------------

  ALTER TABLE "KIRA"."ORDERCOOK" ADD CONSTRAINT "ORD_MMO_FK" FOREIGN KEY ("MNO")
	  REFERENCES "KIRA"."MENU" ("MNO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SAWON
--------------------------------------------------------

  ALTER TABLE "KIRA"."SAWON" ADD CONSTRAINT "SAWON_DEPTNO_FK" FOREIGN KEY ("DEPTNO")
	  REFERENCES "KIRA"."DEPT" ("DEPTNO") ENABLE;
  ALTER TABLE "KIRA"."SAWON" ADD CONSTRAINT "SAWON_SAMGR_FK" FOREIGN KEY ("SAMGR")
	  REFERENCES "KIRA"."SAWON" ("SABUN") ENABLE;
--------------------------------------------------------
--  DDL for Trigger DEPTNO_T
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KIRA"."DEPTNO_T" 
  AFTER UPDATE OF DEPTNO ON DEPT_T
    FOR EACH ROW
  BEGIN
    UPDATE SAWON_T SET DEPTNO = :NEW.DEPTNO WHERE DEPTNO = :OLD.DEPTNO;
END;
/
ALTER TRIGGER "KIRA"."DEPTNO_T" ENABLE;
--------------------------------------------------------
--  DDL for Trigger GOGEK_D
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KIRA"."GOGEK_D" 
AFTER DELETE ON GOGEK
FOR EACH ROW
BEGIN
  DELETE FROM GOGEK_EX
    WHERE gobun = :OLD.gobun;
END;
/
ALTER TRIGGER "KIRA"."GOGEK_D" ENABLE;
--------------------------------------------------------
--  DDL for Trigger GOGEK_I
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "KIRA"."GOGEK_I" 
	AFTER INSERT ON GOGEK
	FOR EACH ROW
	BEGIN
	INSERT INTO GOGEK_EX VALUES(:new.gobun, :new.goname,
:new.gotel, :new.gojumin, :new.godam);
END;
/
ALTER TRIGGER "KIRA"."GOGEK_I" ENABLE;
--------------------------------------------------------
--  DDL for Function F_JUMIN
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "KIRA"."F_JUMIN" (JIMIN VARCHAR2)
RETURN VARCHAR2
IS
  V_GENDER VARCHAR2(10);
BEGIN
  V_GENDER:=SUBSTR(JIMIN,8,1);
  IF V_GENDER='9' OR V_GENDER='1' then
  RETURN '남자';
  ELSE 
  RETURN '여자';
  END IF;
END;

/
--------------------------------------------------------
--  DDL for Function F_NAME
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "KIRA"."F_NAME" (NAME VARCHAR2)
RETURN VARCHAR2
IS
    V_NAME VARCHAR2(10);
BEGIN
    V_NAME:=substr(NAME,2,2);
    RETURN V_NAME;
END;

/
--------------------------------------------------------
--  DDL for Procedure GO_IN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "KIRA"."GO_IN" (
NAME IN GOGEK_PR.GONAME%TYPE,
TEL IN GOGEK_PR.GOTEL%TYPE,
JUMIN IN GOGEK_PR.GOJUMIN%TYPE,
DAM IN GOGEK_PR.GODAM%TYPE)
is
begin
 INSERT INTO GOGEK_PR
 (GOBUN , GONAME , GOTEL , GOJUMIN , GODAM )
 VALUES(GOGEK_SEQ.nextVal , NAME , TEL , JUMIN , DAM );
end;

/
--------------------------------------------------------
--  DDL for Procedure GO_SEARCH
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "KIRA"."GO_SEARCH" (
NAMEKEY IN VARCHAR2, CUR OUT SYS_REFCURSOR)
is
BEGIN
 --1. CURSOR OPEN
 OPEN CUR FOR
 SELECT * FROM GOGEK_PR
 WHERE GONAME = NAMEKEY;
END;

/
--------------------------------------------------------
--  DDL for Procedure GO_SEARCH2
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "KIRA"."GO_SEARCH2" (
NAMEKEY IN VARCHAR2, CUR OUT SYS_REFCURSOR)
is
BEGIN
 --1. CURSOR OPEN
 OPEN CUR FOR
 SELECT GOBUN, GONAME, GOTEL, GOJUMIN, GODAM , 
 DECODE(SUBSTR(GOJUMIN,8,1),'9','남자','1','남자','3','남자','5','남자','7','남자','여자') AS GOGENDER
 FROM GOGEK_PR
 WHERE GONAME = NAMEKEY;
END;

/
--------------------------------------------------------
--  DDL for Procedure PS_IN
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "KIRA"."PS_IN" (
saname in sawon_pr.saname%type,
dno in sawon_pr.deptno%type,
sjob in sawon_pr.sajob%type,
sapay in sawon_pr.sapay%type,
ssex in sawon_pr.sasex%type)
is
begin
	insert into sawon_pr
	(sabun,saname,deptno,sajob,sapay,sahire,sasex)
 	values(sawon_seq.nextVal,saname,dno,sjob,sapay,sysdate,ssex);

end;

/
--------------------------------------------------------
--  DDL for Procedure P_SAWON
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "KIRA"."P_SAWON" -- procedure name
(deptnonum IN number, cur OUT SYS_REFCURSOR)
is
begin
	-- 1. Cursor Open
	open cur for
	select * from sawon
	where deptno = deptnonum;
end;

/
