/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ex1;

import java.awt.CardLayout;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author kosta
 */
public class Sawon extends javax.swing.JFrame {
    private CardLayout card;
    /**
     * Creates new form Sawon
     */
    public Sawon() {
        initComponents();
        card = (CardLayout) pp.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pp = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        deptBtn = new javax.swing.JButton();
        sawonBtn = new javax.swing.JButton();
        gogekBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        deptList = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dnamev = new javax.swing.JTextField();
        locv = new javax.swing.JTextField();
        deptnov = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dList = new javax.swing.JTextArea();
        dept_InsertBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        sawonList = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLab = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sabunv = new javax.swing.JTextField();
        sanamev = new javax.swing.JTextField();
        sadeptnov = new javax.swing.JTextField();
        sapayv = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        sahirev = new javax.swing.JTextField();
        sasexv = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        samgrv = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        sList = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        sajobv = new javax.swing.JTextField();
        gogekList = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        gobunv = new javax.swing.JTextField();
        gonamev = new javax.swing.JTextField();
        gojuminv = new javax.swing.JTextField();
        godamv = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        gogek_insetBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        gList = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        gotelv = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pp.setLayout(new java.awt.CardLayout());

        main.setBackground(new java.awt.Color(204, 255, 204));

        deptBtn.setText("부서관리");
        deptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptBtnActionPerformed(evt);
            }
        });

        sawonBtn.setText("사원관리");
        sawonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sawonBtnActionPerformed(evt);
            }
        });

        gogekBtn.setText("고객관리");
        gogekBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gogekBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("굴림", 0, 36)); // NOI18N
        jLabel1.setText("KOSTA 사내 관리 프로그램");

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addComponent(deptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(sawonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(gogekBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gogekBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sawonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109))
        );

        pp.add(main, "main");

        deptList.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        jLabel2.setText("부서관리");

        jLabel4.setText("부서번호 :");

        jLabel5.setText("부서명 : ");

        jLabel6.setText("지역 :");

        dList.setColumns(20);
        dList.setRows(5);
        jScrollPane1.setViewportView(dList);

        dept_InsertBtn.setText("입력");
        dept_InsertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dept_InsertBtnActionPerformed(evt);
            }
        });

        jButton2.setText("메인");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deptListLayout = new javax.swing.GroupLayout(deptList);
        deptList.setLayout(deptListLayout);
        deptListLayout.setHorizontalGroup(
            deptListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deptListLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(deptListLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(deptListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deptListLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(deptListLayout.createSequentialGroup()
                        .addGroup(deptListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(deptListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deptnov, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(dnamev)
                            .addComponent(locv))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(dept_InsertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176))))
        );
        deptListLayout.setVerticalGroup(
            deptListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deptListLayout.createSequentialGroup()
                .addGroup(deptListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(deptListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deptListLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(deptListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(deptnov, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(deptListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(deptListLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 13, Short.MAX_VALUE))
                            .addComponent(dnamev))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(deptListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(locv, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(deptListLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(dept_InsertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        pp.add(deptList, "c1");

        sawonList.setBackground(new java.awt.Color(153, 153, 255));

        jLabel3.setFont(new java.awt.Font("굴림", 0, 24)); // NOI18N
        jLabel3.setText("사원관리");

        jLab.setText("사원번호");

        jLabel8.setText("사원이름");

        jLabel9.setText("부서번호");

        jLabel10.setText("사원급여");

        jLabel11.setText("입사일");

        jLabel12.setText("성별");

        jLabel13.setText("부서매니저");

        jButton1.setText("메인");

        jButton3.setText("등록");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        sList.setColumns(20);
        sList.setRows(5);
        jScrollPane2.setViewportView(sList);

        jLabel19.setText("사원직책");

        javax.swing.GroupLayout sawonListLayout = new javax.swing.GroupLayout(sawonList);
        sawonList.setLayout(sawonListLayout);
        sawonListLayout.setHorizontalGroup(
            sawonListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sawonListLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(sawonListLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(sawonListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(sawonListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(sawonListLayout.createSequentialGroup()
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(samgrv, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sawonListLayout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sasexv, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sawonListLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sahirev, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sawonListLayout.createSequentialGroup()
                            .addGroup(sawonListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10)
                                .addGroup(sawonListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(sawonListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLab))))
                            .addGroup(sawonListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(sawonListLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(sawonListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(sabunv)
                                        .addComponent(sanamev)
                                        .addComponent(sadeptnov, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)))
                                .addGroup(sawonListLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(sapayv)))))
                    .addGroup(sawonListLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(sajobv, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        sawonListLayout.setVerticalGroup(
            sawonListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sawonListLayout.createSequentialGroup()
                .addGroup(sawonListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sawonListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sawonListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sawonListLayout.createSequentialGroup()
                        .addGroup(sawonListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLab)
                            .addComponent(sabunv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(sawonListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(sanamev, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(sawonListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(sadeptnov, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(sawonListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(sajobv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sawonListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(sapayv, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(sawonListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sahirev, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sawonListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sasexv, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(sawonListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(samgrv, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 77, Short.MAX_VALUE))
        );

        pp.add(sawonList, "c2");

        gogekList.setBackground(new java.awt.Color(204, 102, 255));

        jLabel7.setText("고객관리");

        jLabel14.setText("고객번호");

        jLabel15.setText("고객이름");

        jLabel16.setText("고객주민번호");

        jLabel17.setText("고객담당자");

        gojuminv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gojuminvActionPerformed(evt);
            }
        });

        godamv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                godamvActionPerformed(evt);
            }
        });

        jButton4.setText("메인");

        gogek_insetBtn.setText("등록");
        gogek_insetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gogek_insetBtnActionPerformed(evt);
            }
        });

        gList.setColumns(20);
        gList.setRows(5);
        jScrollPane3.setViewportView(gList);

        jLabel18.setText("고객전화번호");

        gotelv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotelvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gogekListLayout = new javax.swing.GroupLayout(gogekList);
        gogekList.setLayout(gogekListLayout);
        gogekListLayout.setHorizontalGroup(
            gogekListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gogekListLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4))
            .addGroup(gogekListLayout.createSequentialGroup()
                .addGroup(gogekListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(gogekListLayout.createSequentialGroup()
                        .addGroup(gogekListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(42, 42, 42)
                        .addGroup(gogekListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gonamev, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(gobunv)))
                    .addComponent(gogek_insetBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gogekListLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(godamv, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gogekListLayout.createSequentialGroup()
                        .addGroup(gogekListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(gogekListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gotelv, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gojuminv, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
        gogekListLayout.setVerticalGroup(
            gogekListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gogekListLayout.createSequentialGroup()
                .addGroup(gogekListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(gogekListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(gogekListLayout.createSequentialGroup()
                        .addGroup(gogekListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(gobunv, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(gogekListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(gonamev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(gogekListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(gotelv, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(gogekListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(gojuminv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(gogekListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(godamv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addComponent(gogek_insetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 122, Short.MAX_VALUE))
        );

        pp.add(gogekList, "c3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptBtnActionPerformed
        // TODO add your handling code here:
        printDeptList();
        card.show(pp, "c1");
    }//GEN-LAST:event_deptBtnActionPerformed
    
    
    private void sawonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sawonBtnActionPerformed
        // TODO add your handling code here:
        printSawonList();
        card.show(pp, "c2");
    }//GEN-LAST:event_sawonBtnActionPerformed

    private void gogekBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gogekBtnActionPerformed
        // TODO add your handling code here:
        printGogekList();
        card.show(pp, "c3");
    }//GEN-LAST:event_gogekBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dList.setText("");
        card.show(pp, "main");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dept_InsertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dept_InsertBtnActionPerformed
        // TODO add your handling code here:
        insertDept();
    }//GEN-LAST:event_dept_InsertBtnActionPerformed

    private void gojuminvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gojuminvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gojuminvActionPerformed

    private void godamvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_godamvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_godamvActionPerformed

    private void gogek_insetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gogek_insetBtnActionPerformed
        // TODO add your handling code here:
        gList.setText("");
        insertGogek();
    }//GEN-LAST:event_gogek_insetBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        sList.setText("");
        insertSawon();
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void gotelvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotelvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gotelvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sawon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sawon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sawon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sawon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sawon().setVisible(true);
            }
        });
    }
    
    
    
    //==============================SQL METHOD ===================================
    //==============================SQL METHOD ===================================
    //==============================SQL METHOD ===================================
    
    
    public void insertSawon(){
        Connection conn = null;
        PreparedStatement psmt = null;
        ResultSet rs = null;
         try {
            conn = MyConn.getCon();
            int sabun = Integer.parseInt(sabunv.getText().trim());
            String saname = sanamev.getText().trim();
            int deptno = Integer.parseInt(sadeptnov.getText().trim());
            String sajob = sajobv.getText().trim();
            int sapay = Integer.parseInt(sapayv.getText().trim());
            String sahire = sahirev.getText().trim();
            String sasex = sasexv.getText().trim();
            int samgr = Integer.parseInt(samgrv.getText().trim());
            //INSERT INTO SAWON VALUES (SABUN,
            // SANAME,
//            DEPTNO,
//            SAJOB,
//            SAPAY,
//            SAHIRE,
//            SASEX,
//            SAMGR
//            )
            String sql = "INSERT INTO SAWON VALUES ( ? , ? , ? , ? , ? , ? , ? , ? )";
            psmt = conn.prepareStatement(sql);
            psmt.setInt(1, sabun);
            psmt.setString(2, saname);
            psmt.setInt( 3, deptno);
            psmt.setString( 4, sajob);
            psmt.setInt( 5, sapay);
            psmt.setString( 6, sahire);
            psmt.setString(7, sasex);
            psmt.setInt( 8, samgr);
            psmt.executeUpdate();
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, "SQL 오류 ! ");
           ex.printStackTrace();
        } catch (IOException ex) {
           ex.printStackTrace();
        }
        
        
        
    } // insertSawon()
    
    public void printSawonList(){
        Connection conn = null;
        PreparedStatement psmt = null;
        ResultSet rs = null;
        
        try {
            conn = MyConn.getCon();
            String sql = "SELECT * FROM SAWON";
            psmt = conn.prepareStatement(sql);
            rs=psmt.executeQuery();
            while (rs.next()) {
                sList.append("사원 번호 : "+rs.getInt("SABUN")+"\n");
                sList.append("사원 이름 : "+rs.getString("SANAME")+"\n");
                sList.append("부서 번호 : "+rs.getInt("DEPTNO")+"\n");
                sList.append("사원 직책 : "+rs.getString("SAJOB")+"\n");
                sList.append("사원 급여 : "+rs.getInt("SAPAY")+"\n");
                sList.append("사원 입사일 : "+rs.getString("SAHIRE")+"\n");
                sList.append("사원 성별 : "+rs.getString("SASEX")+"\n");
                sList.append("사원매니저 : "+rs.getInt("SAMGR")+"\n");
                sList.append("======================================\n");
                
            }
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, "SQL 오류 ! ");
           ex.printStackTrace();
        } catch (IOException ex) {
           ex.printStackTrace();
        } finally{
            try {
                if (rs != null )  rs.close();
                if (psmt != null )  psmt.close();
                if (conn != null )  conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
        
        
    } // printSawonList()
    
    
    
    public void insertGogek(){
        Connection conn = null;
        PreparedStatement psmt = null;
        ResultSet rs = null;
        
         try {
            conn = MyConn.getCon();
            int gobun = Integer.parseInt(gobunv.getText().trim());
            String goname = gonamev.getText().trim();
            String gotel = gotelv.getText().trim();
            String gojumin = gojuminv.getText().trim();
            int godam = Integer.parseInt(godamv.getText().trim());
            // INSERT INTO GOGEK VALUES (11, 'dd' ,'123-456','900123-123134', 18);
            String sql = "INSERT INTO GOGEK VALUES ( ? , ? , ? , ? , ? )";
            psmt = conn.prepareStatement(sql);
            // 바인딩 
            psmt.setInt(1, gobun);
            psmt.setString(2, goname);
            psmt.setString(3, gotel);
            psmt.setString(4, gojumin);
            psmt.setInt(5, godam);
            // 쿼리 실행 
            psmt.executeUpdate();
            // 갱신
            gobunv.setText("");
            gonamev.setText("");
            gotelv.setText("");
            gojuminv.setText("");
            godamv.setText("");
            printGogekList();
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, "SQL 오류 ! ");
           ex.printStackTrace();
        } catch (IOException ex) {
           ex.printStackTrace();
        }
        
    } // insertGogek()
    
    
    
    public void printGogekList(){
        Connection conn = null;
        PreparedStatement psmt = null;
        ResultSet rs = null;
         try {
            conn = MyConn.getCon();
            
            String sql = "SELECT * FROM GOGEK";
            psmt = conn.prepareStatement(sql);
            rs = psmt.executeQuery();
            while (rs.next()) {
                gList.append("고객 번호 : " +rs.getInt("GOBUN")+"\n");
                gList.append("고객 이름 : " +rs.getString("GONAME")+"\n");
                gList.append("고객 전화번호 : " +rs.getString("GOTEL")+"\n");
                gList.append("고객 주민번호 : " +rs.getString("GOJUMIN")+"\n");
                gList.append("고객 담당자 : "+rs.getInt("GODAM")+"\n");
                gList.append("========================================"+"\n"); 
            }
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(this, "SQL 오류 ! ");
           ex.printStackTrace();
        } catch (IOException ex) {
           ex.printStackTrace();
        }finally{
            try {
                if (rs != null )  rs.close();
                if (psmt != null )  psmt.close();
                if (conn != null )  conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
        
    } // printGogekList()
    
    
    
    
    
    
    
    
    public void insertDept(){
        Connection conn = null;
        PreparedStatement pstm = null;
        ResultSet rs = null;
        try {
            conn = MyConn.getCon();
            Integer deptno = Integer.parseInt(deptnov.getText().trim());
            String dname = dnamev.getText().trim();
            String loc = locv.getText().trim();
            
            StringBuffer sql = new StringBuffer();
            sql.append("INSERT INTO DEPT VALUES ( ? , ? , ?)");
            pstm = conn.prepareStatement(sql.toString());
            // 바인딩 
            pstm.setInt(1, deptno);
            pstm.setString(2, dname);
            pstm.setString(3, loc);
            // 바인딩 값을 전송 
            System.out.println("LOG sql(dept-insert) : "+sql);
            // 바인딩된 값을 전송 
            // insert , update, delete 는 모두 executeUpdate();
            // Select 는 pstm.executeQuery()
            pstm.executeUpdate();
            
            // deptList 갱신 및 입력 폼 초기화 
            deptnov.setText("");
            dnamev.setText("");
            locv.setText("");
            deptnov.requestFocus();
            printDeptList();
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(this, "잘못된 오류입니다.");
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        } finally{
            try {
                if(pstm !=null )pstm.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
        
    } // end insertDept()
    
    
    public void printDeptList(){
        Connection conn = null; 
        PreparedStatement  pstm= null;
        ResultSet rs = null;
        
        try {
            conn = MyConn.getCon();
            StringBuffer sql = new StringBuffer();
            sql.append("SELECT DEPTNO , DNAME , LOC FROM DEPT ")
               .append(" ORDER BY 1 DESC");
            System.out.println("Log sql(dept-SELECT) : "+sql);
            pstm = conn.prepareStatement(sql.toString());
            rs = pstm.executeQuery();
            // rs.next() : 다음 Cursor 가 있으면 참 
            while (rs.next()) {
                dList.append("부서번호 :" +rs.getInt("DEPTNO")+"\n");
                dList.append("부서이름 : "+rs.getString("DNAME")+"\n");
                dList.append("부서위치 :" +rs.getString("LOC")+"\n");
                dList.append("=========================================\n");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        } finally{
            try {
                if (rs != null )  rs.close();
                if (pstm != null )  pstm.close();
                if (conn != null )  conn.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    } // end printDeptList()
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea dList;
    private javax.swing.JButton deptBtn;
    private javax.swing.JPanel deptList;
    private javax.swing.JButton dept_InsertBtn;
    private javax.swing.JTextField deptnov;
    private javax.swing.JTextField dnamev;
    private javax.swing.JTextArea gList;
    private javax.swing.JTextField gobunv;
    private javax.swing.JTextField godamv;
    private javax.swing.JButton gogekBtn;
    private javax.swing.JPanel gogekList;
    private javax.swing.JButton gogek_insetBtn;
    private javax.swing.JTextField gojuminv;
    private javax.swing.JTextField gonamev;
    private javax.swing.JTextField gotelv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField locv;
    private javax.swing.JPanel main;
    private javax.swing.JPanel pp;
    private javax.swing.JTextArea sList;
    private javax.swing.JTextField sabunv;
    private javax.swing.JTextField sadeptnov;
    private javax.swing.JTextField sahirev;
    private javax.swing.JTextField sajobv;
    private javax.swing.JTextField samgrv;
    private javax.swing.JTextField sanamev;
    private javax.swing.JTextField sapayv;
    private javax.swing.JTextField sasexv;
    private javax.swing.JButton sawonBtn;
    private javax.swing.JPanel sawonList;
    // End of variables declaration//GEN-END:variables
}
