
import ex1.dao.BoardDao;
import ex1.vo.BoardVo;
import java.awt.CardLayout;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kosta
 */
public class BoardTest extends javax.swing.JFrame {
    private CardLayout card;
    /**
     * Creates new form BoardTest
     */
    public BoardTest() {
        initComponents();
        card = (CardLayout) pp.getLayout();
        showList();
        card.show(pp, "bList");
    }
    
    public void showList(){
        boardListv.setText("");
        BoardDao dao = new BoardDao();
        ArrayList<BoardVo> list = dao.getList();
        for (BoardVo list1 : list) {
            boardListv.append("NUM : "+ list1.getNum()+"\n");
            boardListv.append("SUB : "+ list1.getSub()+"\n");
            boardListv.append("Writer : "+ list1.getWriter()+"\n");
            boardListv.append("Redate : "+ list1.getRedate()+"\n");
            boardListv.append("==================================\n");
        }
    }
    
    public void add() throws UnknownHostException{
        BoardVo vo = new BoardVo();
        BoardDao dao = new BoardDao();
        vo.setSub(subv.getText().trim());
        vo.setWriter(writerv.getText().trim());
        vo.setPwd(pwdv.getText().trim());
        vo.setCont(contentv.getText().trim());
        String reip = InetAddress.getLocalHost().getHostAddress();
        vo.setReip(reip);
        boolean res =dao.insertBoard(vo);
        
        String msg = "";
        if (res) {
            msg = "게시물이 등록 되었습니다.";
        } else {
            msg = "시스템에 문제가 발생되어 등록되지 못했습니다.";
        }
        JOptionPane.showMessageDialog(this, msg);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pp = new javax.swing.JPanel();
        boardList = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        boardListv = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        deletev = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        bformMoveBtn = new javax.swing.JButton();
        boardForm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pwdv = new javax.swing.JPasswordField();
        writerv = new javax.swing.JTextField();
        subv = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentv = new javax.swing.JTextArea();
        insertBtn = new javax.swing.JButton();
        ListMoveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pp.setLayout(new java.awt.CardLayout());

        boardListv.setColumns(20);
        boardListv.setRows(5);
        jScrollPane2.setViewportView(boardListv);

        jLabel4.setText("삭제");

        deleteBtn.setText("delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jButton3.setText("detail");

        bformMoveBtn.setText("작성폼");
        bformMoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bformMoveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout boardListLayout = new javax.swing.GroupLayout(boardList);
        boardList.setLayout(boardListLayout);
        boardListLayout.setHorizontalGroup(
            boardListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boardListLayout.createSequentialGroup()
                .addGroup(boardListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boardListLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardListLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(deletev, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bformMoveBtn)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        boardListLayout.setVerticalGroup(
            boardListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boardListLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(boardListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(deletev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn)
                    .addComponent(jButton3)
                    .addComponent(bformMoveBtn))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        pp.add(boardList, "bList");

        jLabel1.setText("제목");

        jLabel2.setText("작성자");

        jLabel3.setText("비밀번호");

        contentv.setColumns(20);
        contentv.setRows(5);
        jScrollPane1.setViewportView(contentv);

        insertBtn.setText("등록");
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });

        ListMoveBtn.setText("리스트");
        ListMoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListMoveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout boardFormLayout = new javax.swing.GroupLayout(boardForm);
        boardForm.setLayout(boardFormLayout);
        boardFormLayout.setHorizontalGroup(
            boardFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boardFormLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(boardFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(boardFormLayout.createSequentialGroup()
                        .addGroup(boardFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(boardFormLayout.createSequentialGroup()
                                .addGroup(boardFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boardFormLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)))
                        .addGroup(boardFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(subv, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                            .addComponent(writerv)
                            .addComponent(pwdv)))
                    .addGroup(boardFormLayout.createSequentialGroup()
                        .addComponent(insertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ListMoveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(424, Short.MAX_VALUE))
        );
        boardFormLayout.setVerticalGroup(
            boardFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boardFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(boardFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(boardFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(writerv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(boardFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(boardFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(insertBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(ListMoveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pp.add(boardForm, "bForm");

        getContentPane().add(pp, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed
        try {
            // TODO add your handling code here:
            add();
        } catch (UnknownHostException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_insertBtnActionPerformed

    private void ListMoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListMoveBtnActionPerformed
        // TODO add your handling code here:
        showList();
        card.show(pp, "bList");
    }//GEN-LAST:event_ListMoveBtnActionPerformed

    private void bformMoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bformMoveBtnActionPerformed
        // TODO add your handling code here:
        card.show(pp, "bForm");
    }//GEN-LAST:event_bformMoveBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        BoardDao dao = new BoardDao();
        String msg = "";
        try {
            int delN = Integer.parseInt(deletev.getText().trim());
            int res = dao.delete(delN);
            if (res > 0) msg ="삭제 성공" ;
        } catch (NumberFormatException e) {
            msg = "정수입력";
            deletev.setText("");
            deletev.requestFocus();
        }
        JOptionPane.showMessageDialog(this, msg);
        showList();
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoardTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoardTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoardTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoardTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoardTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ListMoveBtn;
    private javax.swing.JButton bformMoveBtn;
    private javax.swing.JPanel boardForm;
    private javax.swing.JPanel boardList;
    private javax.swing.JTextArea boardListv;
    private javax.swing.JTextArea contentv;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField deletev;
    private javax.swing.JButton insertBtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pp;
    private javax.swing.JPasswordField pwdv;
    private javax.swing.JTextField subv;
    private javax.swing.JTextField writerv;
    // End of variables declaration//GEN-END:variables
}
